export const LNG = {
  ko: 'ko',
  ko_KR: 'ko-KR',
  zh: 'zh',
  zh_TW: 'zh-TW',
  vi: 'vi',
  vi_VN: 'vi-VN',
  en: 'en',
  en_US: 'en-US',
  en_150: 'en-150',
  en_AU: 'en-AU',
  en_CA: 'en-CA',
  en_GB: 'en-GB',
  en_NZ: 'en-NZ',
  en_US_POSIX: 'en-US-POSIX',
};
